<div class="footer-top">
    Copyright © 2017 / DGMD E-27 - A Student Project by Jai
</div>

<div class="searchbox-mobile">
    <form>
        <input type="text" placeholder="Search..." required><br>
        <input type="button" class="search-btn" value="Search">
    </form>
</div>


<div class="footer-links">
    <div class="menu-group-01">
        <nav class="menu-item menu-places">
            <h3>Places</h3>
            <ul>
                <?php include("pages/places/01-parts/03-navigation_places.inc"); ?>
            </ul>
        </nav>
        <nav class="menu-item menu-links">
            <h4>Links</h4>
            <ul>
                <li><a href="">Travel Services</a></li>
                <li><a href="">About Us</a></li>
                <li><a href="">Contact Us</a></li>
            </ul>
        </nav>
    </div>
</div>


<div class="footer-sponsors">
    <h3>Our Sponsors:</h3>
    <img src="asset/img/sponsors/logo01.png" alt="Sponsor 1">
    <img src="asset/img/sponsors/logo02.png" alt="Sponsor 2">
    <img src="asset/img/sponsors/logo03.png" alt="Sponsor 3">
    <img src="asset/img/sponsors/logo04.png" alt="Sponsor 4">
    <img src="asset/img/sponsors/logo05.png" alt="Sponsor 5">
    <img src="asset/img/sponsors/logo06.png" alt="Sponsor 6">
    <img src="asset/img/sponsors/logo07.png" alt="Sponsor 7">
    <img src="asset/img/sponsors/logo08.png" alt="Sponsor 8">
    <img src="asset/img/sponsors/logo09.png" alt="Sponsor 9">
    <img src="asset/img/sponsors/logo10.png" alt="Sponsor 10">
    <img src="asset/img/sponsors/logo11.png" alt="Sponsor 11">
    <img src="asset/img/sponsors/logo12.png" alt="Sponsor 12">
    <img src="asset/img/sponsors/logo13.png" alt="Sponsor 13">
    <img src="asset/img/sponsors/logo08.png" alt="Sponsor 14">
    <img src="asset/img/sponsors/logo09.png" alt="Sponsor 15">
    <img src="asset/img/sponsors/logo10.png" alt="Sponsor 16">
    <img src="asset/img/sponsors/logo01.png" alt="Sponsor 17">
    <img src="asset/img/sponsors/logo02.png" alt="Sponsor 18">
    <img src="asset/img/sponsors/logo03.png" alt="Sponsor 19">
    <img src="asset/img/sponsors/logo04.png" alt="Sponsor 20">

</div>

<div class="social-media-mobile">
    <nav>
        <ul>
            <li><a target="_blank" href="https://www.facebook.com/funda.web.3"><img
                        src="asset/img/social-media/fb_icon.png" alt="Footer link to facebook page"></a></li>
            <li><a target="_blank" href="https://www.facebook.com/funda.web.3"><img
                        src="asset/img/social-media/twitter_icon.jpg" alt="Footer link to twitter page"></a>
            </li>
            <li><a target="_blank" href="https://www.facebook.com/funda.web.3"><img
                        src="asset/img/social-media/instagram_icon.png"
                        alt="Footer link to Instagram page"></a></li>
            <li><a target="_blank" href="https://www.facebook.com/funda.web.3"><img
                        src="asset/img/social-media/pinterest_icon.png"
                        alt="Footer link to Pinterest page"></a></li>
            <li><a target="_blank" href="https://www.facebook.com/funda.web.3"><img
                        src="asset/img/social-media/googleplus_icon.png" alt="Footer link to Google Plus page"></a>
            </li>
        </ul>
    </nav>
</div>

<div class="thanks-to">
    <h3>Thanks to:</h3>
    <nav>
        <ul>
            <li><a href="http://www.bigstockphotos.com" target="_blank" >Big Stock Photos - Provided images</a></li>
            <li><a href="https://www.dreamstime.com" target="_blank" >DreamsTimes - Provided images</a></li>
            <li><a href="https://vectormagic.com/" target="_blank" >Vector Magic - Bitmap to vector</a></li>
            <li><a href="https://scottjehl.github.io/picturefill/" target="_blank" >Picturefill.js - Image swap</a></li>
            <li><a href="http://cssmenumaker.com/" target="_blank" >CSSMenuMaker - Hamburger menu</a></li>
            <li><a href="http://imageslidermaker.com/v2" target="_blank" >ImageSliderMaker v2 - Hero image sliders</a></li>
            <li><a href="https://www.gimp.org/" target="_blank" >Gimp - Graphics Editor</a></li>
            <li><a href="http://mobiledetect.net/" target="_blank">PHP Mobile Detect</a></li>
            <li><a href="http://mp3caprice.com/" target="_blank">MP3 Caprice</a></li>

        </ul>
    </nav>
</div>
<!--
<audio autoplay loop>
    <source src="/asset/audio/empirestate.mp3" type="audio/mpeg">
    Your browser does not support the audio element.
</audio>
-->